# yaml-language-server: $schema=../docs/schema.json
changelog:
  exclude:
    labels:
      - documentation
      - duplicate
      - invalid
    authors:
      - github-actions[bot]
  categories:
    - title: Breaking Changes
      labels: [breaking]
      version: major
    - title: New Features
      labels: [enhancement]
      version: minor
    - title: Bug Fixes
      labels: [bug]
      version: patch
    - title: Dependency Updates
      labels: [dependencies]
      version: patch
    - title: Other Changes
      labels: ["*"]
