name: Setup Dependencies
description: Installs node and deps for the app
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: yarn
    - run: yarn install --prefer-offline --frozen-lockfile
      shell: bash
