name: Autoversion
description: Automatic version generation based on your GitHub generated release notes.
inputs:
  draft:
    description: Whether to mark the release as draft.
    # type: boolean
    default: "true"
  channel:
    description: Optional release channel for the release, starting with "v" and ending with ".x".
outputs:
  bump:
    description: |
      Release type of the version bump if one occurred. Can be "major",
      "premajor", "minor", "preminor", "patch", "prepatch", or "pre". When
      starting with "pre", that indicates this release was a prerelease.
  last:
    description: Last version to have been released
  next:
    description: Next version to be released
runs:
  using: "node20"
  main: "action/dist/index.js"
