name: Bug Report
description: Something went wrong? Tell us about it!
labels: [bug]
assignees: [tubbo]
body:
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: Also tell us, what did you expect to happen?
      placeholder: A clear and concise description of the bug.
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Copy/paste the log output from the action run
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our code of conduct.
      options:
        - label: I agree
          required: true
