name: Build
on:
  workflow_call:
  pull_request:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: ${{ github.event_name == "pull_request" }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - run: yarn lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - run: yarn test
  dist:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: ./.github/actions/setup
      - run: yarn build
      - uses: actions/upload-artifact@v4
        with:
          path: dist/
