name: Dependencies
on:
  pull_request:
    branches: [main]
permissions:
  pull-requests: write
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
  merge:
    runs-on: ubuntu-latest
    needs: review
    if: github.actor == 'dependabot[bot]'
    env:
      GH_TOKEN: ${{ github.token }}
      PR: ${{ github.event.pull_request.html_url }}
    steps:
      - run: gh pr review --approve "$PR"
      - run: gh pr merge --auto "$PR"
