name: Release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * MON" # every monday at 2pm eastern
concurrency: ${{ github.workflow }}-${{ github.ref_name }}
jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: fregante/setup-git-user@v2
      - uses: ./
        id: version
      - if: steps.version.outputs.bumped == "true"
        run: |-
          gh release create v${{ steps.version.outputs.next }} --generate-notes
          git tag --force v${{ steps.version.outputs.major }}
          git push --force v${{ steps.version.outputs.major }}
