name: Release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * MON" # every monday at 2pm eastern
concurrency: ${{ github.workflow }}-${{ github.ref_name }}
jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: dist/
      - uses: ./
        id: version
      - if: steps.version.outputs.bumped == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.next }}
          generate_release_notes: true
      - if: steps.version.outputs.bumped == 'true'
        uses: JasonEtco/build-and-tag-action@v2
        with:
          tag_name: v${{ steps.version.outputs.next }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
